name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Node version
        run: node --version
      - name: Install
        run: npm install
      - name: Check TypeScript
        run: yarn check_typescript
      - name: Build
        run: yarn build
      - name: Unit Test
        run: yarn unit_test
      - name: Integration Test
        run: yarn integration_test
